[package]
name = "network"
version = "0.0.1"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
bincode = { "version" = "1.0", features = ["i128"] }
byteorder = "1.2.7"
futures = "0.1"
tokio = "0.1"
tokio-codec = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
bytes = "0.2"
env_logger = "0.5"
rand = "0.6"
tokio-serde-cbor = "0.3"
log = "0.4"
parking_lot = "0.7.1"

primitives = { path = "../../core/primitives" }
transaction = { path = "../../core/transaction" }
storage = { path = "../../core/storage" }
chain = { path = "../../core/chain" }
beacon = { path = "../../node/beacon" }
configs = { path = "../configs" }
client = { path = "../../node/client" }
shard = { path = "../../core/shard" }

[features]
test-utils = []
